In [4]:
import pandas as pd

flight_delays = pd.read_csv("delays.csv")
flight_fares_with_weather = pd.read_csv("fares_distances_weather.csv")

In [5]:
flight_delays.head()

Departing_Port Arriving_Port  Airline        Date  Departure_Delays_%  \
0       Adelaide      Brisbane  Jetstar  2010-01-01            0.266667   
1       Adelaide    Gold Coast  Jetstar  2010-01-01            0.166667   
2       Adelaide     Melbourne  Jetstar  2010-01-01            0.255319   
3       Adelaide         Perth  Jetstar  2010-01-01            0.137931   
4       Adelaide        Sydney  Jetstar  2010-01-01            0.118644   

   Arrival_Delays_%  Cancellations_%  
0          0.233333              0.0  
1          0.166667              0.0  
2          0.234043              0.0  
3          0.103448              0.0  
4          0.322034              0.0

In [6]:
flight_fares_with_weather.head()

Departing_Port Arriving_Port  Month  Year  Average_Fare     Distance  \
0       Adelaide      Brisbane      8  2010         157.0  1619.982414   
1       Adelaide      Canberra      8  2010         350.0   970.229046   
2       Adelaide    Gold Coast      8  2010         232.0  1604.162840   
3       Adelaide     Melbourne      8  2010          87.0   641.652927   
4       Adelaide         Perth      8  2010         406.0  2115.440208   

    MinTemp    MaxTemp  Rainfall  Evaporation  ...  WindSpeed3pm  Humidity9am  \
0  7.039858  16.730247  2.423597     3.102688  ...     19.611588     72.25107   
1  7.039858  16.730247  2.423597     3.102688  ...     19.611588     72.25107   
2  7.039858  16.730247  2.423597     3.102688  ...     19.611588     72.25107   
3  7.039858  16.730247  2.423597     3.102688  ...     19.611588     72.25107   
4  7.039858  16.730247  2.423597     3.102688  ...     19.611588     72.25107   

   Humidity3pm  Pressure9am  Pressure3pm  Cloud9am  Cloud3pm    Temp9am  \
0    54.674699  1017.589078  1014.939908  4.275437  4.529652  11.515598   
1    54.674699  1017.589078  1014.939908  4.275437  4.529652  11.515598   
2    54.674699  1017.589078  1014.939908  4.275437  4.529652  11.515598   
3    54.674699  1017.589078  1014.939908  4.275437  4.529652  11.515598   
4    54.674699  1017.589078  1014.939908  4.275437  4.529652  11.515598   

     Temp3pm   Day  
0  15.568909  16.0  
1  15.568909  16.0  
2  15.568909  16.0  
3  15.568909  16.0  
4  15.568909  16.0  

[5 rows x 23 columns]

In [8]:
flight_delays["Date"] = pd.to_datetime(flight_delays["Date"])

In [10]:
flight_delays["Month"] = flight_delays["Date"].apply(lambda x: x.month)
flight_delays["Year"] = flight_delays["Date"].apply(lambda x: x.year)

In [11]:
flight_delays

Departing_Port Arriving_Port                             Airline  \
0           Adelaide      Brisbane                             Jetstar   
1           Adelaide    Gold Coast                             Jetstar   
2           Adelaide     Melbourne                             Jetstar   
3           Adelaide         Perth                             Jetstar   
4           Adelaide        Sydney                             Jetstar   
...              ...           ...                                 ...   
59377          Perth    Kalgoorlie  Virgin Australia Regional Airlines   
59378          Perth      Karratha  Virgin Australia Regional Airlines   
59379          Perth        Newman  Virgin Australia Regional Airlines   
59380          Perth  Port Hedland  Virgin Australia Regional Airlines   
59381   Port Hedland         Perth  Virgin Australia Regional Airlines   

            Date  Departure_Delays_%  Arrival_Delays_%  Cancellations_%  \
0     2010-01-01            0.266667          0.233333         0.000000   
1     2010-01-01            0.166667          0.166667         0.000000   
2     2010-01-01            0.255319          0.234043         0.000000   
3     2010-01-01            0.137931          0.103448         0.000000   
4     2010-01-01            0.118644          0.322034         0.000000   
...          ...                 ...               ...              ...   
59377 2024-02-01            0.157895          0.210526         0.052632   
59378 2024-02-01            0.142857          0.071429         0.000000   
59379 2024-02-01            0.076923          0.153846         0.000000   
59380 2024-02-01            0.166667          0.166667         0.083333   
59381 2024-02-01            0.538462          0.461538         0.153846   

       Month  Year  
0          1  2010  
1          1  2010  
2          1  2010  
3          1  2010  
4          1  2010  
...      ...   ...  
59377      2  2024  
59378      2  2024  
59379      2  2024  
59380      2  2024  
59381      2  2024  

[59382 rows x 9 columns]

In [14]:
import numpy as np
np.unique(flight_delays.Year)

array([2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020,
       2021, 2022, 2023, 2024], dtype=int64)

In [18]:
import numpy as np
for year in list(np.unique(flight_delays.Year)):

    data = flight_delays.loc[flight_delays["Year"] == year]

    months = data["Month"]

    print(year)
    print(np.unique(months))

2010
[ 1  2  3  4  5  6  7  8  9 10 11 12]
2011
[ 1  2  3  4  5  6  7  8  9 10 11 12]
2012
[ 1  2  3  4  5  6  7  8  9 10 11 12]
2013
[ 1  2  3  4  5  6  7  8  9 10 11 12]
2014
[ 1  2  3  4  5  6  7  8  9 10 11 12]
2015
[ 1  2  3  4  5  6  7  8  9 10 11 12]
2016
[ 1  2  3  4  5  6  7  8  9 10 11 12]
2017
[ 1  2  3  4  5  6  7  8  9 10 11 12]
2018
[ 1  2  3  4  5  6  7  8  9 10 11 12]
2019
[ 1  2  3  4  5  6  7  8  9 10 11 12]
2020
[ 1  2  3  4  5  6  7  8  9 10 11 12]
2021
[ 1  2  3  4  5  6  7  8  9 10 11 12]
2022
[ 1  2  3  4  5  6  7  8  9 10 11 12]
2023
[ 1  2  3  4  5  6  7  8  9 10 11 12]
2024
[1 2]


In [22]:
combined_data = pd.merge(
    left=flight_fares_with_weather,
    right=flight_delays,
    how='outer',
    left_on=['Month', 'Year', 'Departing_Port', 'Arriving_Port'],
    right_on=['Month', 'Year', 'Departing_Port', 'Arriving_Port'],
)

In [26]:
combined_data = combined_data.dropna()

In [27]:
del combined_data["Day"]
del combined_data["Date"]

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 2895, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Day'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3418, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-27-62f96e7098bf>", line 1, in <module>
    del combined_data["Day"]
  File "C:\ProgramData\Anaconda3\lib\site-pac

TypeError: object of type 'NoneType' has no len()

In [28]:
combined_data

Departing_Port Arriving_Port  Month  Year  Average_Fare     Distance  \
0            Adelaide      Brisbane      8  2010         157.0  1619.982414   
1            Adelaide      Brisbane      8  2010         157.0  1619.982414   
2            Adelaide      Brisbane      8  2010         157.0  1619.982414   
3            Adelaide      Brisbane      8  2010         157.0  1619.982414   
4            Adelaide      Canberra      8  2010         350.0   970.229046   
...               ...           ...    ...   ...           ...          ...   
61430  Sunshine Coast     Melbourne      7  2010         414.0  1453.957673   
61431          Sydney   Wagga Wagga      7  2010         414.0   365.844014   
61432          Sydney   Wagga Wagga      7  2010         414.0   365.844014   
61433          Sydney    Townsville      7  2010         414.0  1691.132106   
61434          Sydney    Townsville      7  2010         414.0  1691.132106   

        MinTemp    MaxTemp  Rainfall  Evaporation  ...  Pressure9am  \
0      7.039858  16.730247  2.423597     3.102688  ...  1017.589078   
1      7.039858  16.730247  2.423597     3.102688  ...  1017.589078   
2      7.039858  16.730247  2.423597     3.102688  ...  1017.589078   
3      7.039858  16.730247  2.423597     3.102688  ...  1017.589078   
4      7.039858  16.730247  2.423597     3.102688  ...  1017.589078   
...         ...        ...       ...          ...  ...          ...   
61430  6.961549  16.439830  2.435533     2.219612  ...  1023.556308   
61431  6.961549  16.439830  2.435533     2.219612  ...  1023.556308   
61432  6.961549  16.439830  2.435533     2.219612  ...  1023.556308   
61433  6.961549  16.439830  2.435533     2.219612  ...  1023.556308   
61434  6.961549  16.439830  2.435533     2.219612  ...  1023.556308   

       Pressure3pm  Cloud9am  Cloud3pm    Temp9am    Temp3pm  \
0      1014.939908  4.275437  4.529652  11.515598  15.568909   
1      1014.939908  4.275437  4.529652  11.515598  15.568909   
2      1014.939908  4.275437  4.529652  11.515598  15.568909   
3      1014.939908  4.275437  4.529652  11.515598  15.568909   
4      1014.939908  4.275437  4.529652  11.515598  15.568909   
...            ...       ...       ...        ...        ...   
61430  1021.219584  4.746964  5.162051  10.580601  15.363305   
61431  1021.219584  4.746964  5.162051  10.580601  15.363305   
61432  1021.219584  4.746964  5.162051  10.580601  15.363305   
61433  1021.219584  4.746964  5.162051  10.580601  15.363305   
61434  1021.219584  4.746964  5.162051  10.580601  15.363305   

                  Airline  Departure_Delays_%  Arrival_Delays_%  \
0                 Jetstar            0.451613          0.290323   
1                  Qantas            0.067961          0.097087   
2      Tigerair Australia            0.227273          0.227273   
3        Virgin Australia            0.150538          0.086022   
4                  Qantas            0.061224          0.040816   
...                   ...                 ...               ...   
61430    Virgin Australia            0.416667          0.333333   
61431          QantasLink            0.307018          0.412281   
61432    Regional Express            0.165468          0.230216   
61433             Jetstar            0.136364          0.045455   
61434    Virgin Australia            0.354839          0.387097   

       Cancellations_%  
0             0.000000  
1             0.000000  
2             0.000000  
3             0.021505  
4             0.000000  
...                ...  
61430         0.027778  
61431         0.017544  
61432         0.028777  
61433         0.000000  
61434         0.000000  

[30116 rows x 26 columns]

In [30]:
# Sort the data by date (earliest to latest)

combined_data = combined_data.sort_values(by=["Year", "Month"]).reset_index(drop=True)

In [31]:
combined_data

Departing_Port Arriving_Port  Month  Year  Average_Fare    Distance  \
0           Adelaide     Melbourne      1  2010         414.0  641.652927   
1           Adelaide     Melbourne      1  2010         414.0  641.652927   
2           Adelaide     Melbourne      1  2010         414.0  641.652927   
3           Adelaide     Melbourne      1  2010         414.0  641.652927   
4           Adelaide      Canberra      1  2010         414.0  970.229046   
...              ...           ...    ...   ...           ...         ...   
30111       Moranbah      Brisbane      6  2017        1277.0  779.683481   
30112       Armidale        Sydney      6  2017         326.0  382.268024   
30113       Armidale        Sydney      6  2017         326.0  382.268024   
30114       Tamworth        Sydney      6  2017         643.0  319.769513   
30115       Tamworth        Sydney      6  2017         643.0  319.769513   

        MinTemp    MaxTemp  Rainfall  Evaporation  ...  Pressure9am  \
0      17.33103  29.763540  2.198292     8.894267  ...  1013.053858   
1      17.33103  29.763540  2.198292     8.894267  ...  1013.053858   
2      17.33103  29.763540  2.198292     8.894267  ...  1013.053858   
3      17.33103  29.763540  2.198292     8.894267  ...  1013.053858   
4      17.33103  29.763540  2.198292     8.894267  ...  1013.053858   
...         ...        ...       ...          ...  ...          ...   
30111   7.14584  18.217691  1.944638     2.741813  ...  1025.984182   
30112   7.14584  18.217691  1.944638     2.741813  ...  1025.984182   
30113   7.14584  18.217691  1.944638     2.741813  ...  1025.984182   
30114   7.14584  18.217691  1.944638     2.741813  ...  1025.984182   
30115   7.14584  18.217691  1.944638     2.741813  ...  1025.984182   

       Pressure3pm  Cloud9am  Cloud3pm    Temp9am    Temp3pm  \
0      1010.905502  4.167756  4.016930  22.526185  27.847663   
1      1010.905502  4.167756  4.016930  22.526185  27.847663   
2      1010.905502  4.167756  4.016930  22.526185  27.847663   
3      1010.905502  4.167756  4.016930  22.526185  27.847663   
4      1010.905502  4.167756  4.016930  22.526185  27.847663   
...            ...       ...       ...        ...        ...   
30111  1023.486260  4.872945  5.115312  11.379967  16.965475   
30112  1023.486260  4.872945  5.115312  11.379967  16.965475   
30113  1023.486260  4.872945  5.115312  11.379967  16.965475   
30114  1023.486260  4.872945  5.115312  11.379967  16.965475   
30115  1023.486260  4.872945  5.115312  11.379967  16.965475   

                  Airline  Departure_Delays_%  Arrival_Delays_%  \
0                 Jetstar            0.255319          0.234043   
1                  Qantas            0.087542          0.090909   
2      Tigerair Australia            0.083333          0.033333   
3        Virgin Australia            0.072874          0.068826   
4                  Qantas            0.111111          0.083333   
...                   ...                 ...               ...   
30111    Virgin Australia            0.078431          0.058824   
30112          QantasLink            0.256198          0.297521   
30113    Regional Express            0.278481          0.329114   
30114          QantasLink            0.180645          0.174194   
30115    Virgin Australia            0.156863          0.156863   

       Cancellations_%  
0             0.000000  
1             0.003367  
2             0.050000  
3             0.012146  
4             0.000000  
...                ...  
30111         0.000000  
30112         0.115702  
30113         0.050633  
30114         0.051613  
30115         0.019608  

[30116 rows x 26 columns]

In [34]:
combined_data.to_csv("flights_data.csv", index=False, header=True)